# Generated by Django 3.1.7 on 2021-03-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_production', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='Name_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Id',
            new_name='Id_review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='comment_text',
        ),
    ]
