# Generated by Django 3.1.7 on 2021-03-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_production', '0003_auto_20210330_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
